### PR TITLE
Add new dataset-Chronic diseases indicatprs in the U.S

### PR DESCRIPTION
**Pull request by mohamedsto7y**

### CODE REVIEW

**Comment by henrykironde** [comment]
Good start @mohamedsto7y. Please read through the docs on adding a data package, https://retriever.readthedocs.io/en/latest/recipes.html#basic-scripts

Use the data packages in the script folder as examples. 
Here is an issue that may help https://github.com/weecology/retriever/issues/1555

**Comment by mohamedsto7y** [comment]
Thank you so much.

It is shown now on the retriever ls command.

screenshot

**Comment by henrykironde** [comment]
Make sure you remove the file that is not supposed to be here.
Also run python version.py to update the version.txt
Add and commit. 
In case you are editing, use commit --amend so that you do not have many commit messages.

Make sure there is no 'fill`. The url must be the link to the data

**Comment by mohamedsto7y** [comment]
Thank you so much.
I followed your comments and succeeded to add the script and it shown in the retriever ls command.
Yet,when I  downloaded csv file to check I found it had only one row.
I repeated the process from creating the json file but the issue is still.
Progress show 0 rows


screenshot

**Comment by henrykironde** [comment]
@mohamedsto7y, I made  some comment above. read then and update the PR.

**Pull request closed without merging**
