### PR TITLE
CONUS dataset added

### PR DESCRIPTION
**Pull request by Sohan022**
I have added CONUS dataset.
This issue has mentioned in the retriever repo.
Link: https://github.com/weecology/retriever/issues/1540

### CODE REVIEW

**Comment by henrykironde** [comment]
What commands did you run to test the PR

**Comment by Sohan022** [comment]
`retriever ls` : It is showing `CONUS` dataset in the list.

`retriver citation conus` : It is showing citation of `CONUS` dataset which is written inside the conus.json file.

**Comment by henrykironde** [comment]
Try `retriever install postgres conus`. Open the Postgres database server and check if the tables have data. Take a screenshot

**Comment by Sohan022** [comment]
I have run the command `retriever install postgres conus`
```
sohan@ubuntu-user:~$ retriever install postgres conus
=> Installing conus
Creating database conus...

schema "conus" already exists

Installing into existing database
Downloading CONUS_Backcasting_y1981.tif: 13.6kB [04:25, 52.4B/s]                                                                                                         
Processing 1/1: /home/sohan/.retriever/raw_data/conus/CONUS_Backcasting_y1981.tif
NOTICE:  table "conus_backcasting_y1981" does not exist, skipping
Downloading CONUS_Backcasting_y1960.tif: 13.8kB [05:07, 45.9B/s]                                                                                                         
Processing 1/1: /home/sohan/.retriever/raw_data/conus/CONUS_Backcasting_y1960.tif
NOTICE:  table "conus_backcasting_y1960" does not exist, skipping
Downloading CONUS_Backcasting_y1975.tif: 13.7kB [05:59, 38.9B/s]                                                                                                         
Processing 1/1: /home/sohan/.retriever/raw_data/conus/CONUS_Backcasting_y1975.tif
NOTICE:  table "conus_backcasting_y1975" does not exist, skipping
Downloading CONUS_Backcasting_y1958.tif: 13.8kB [05:13, 45.0B/s]                                                                                                         
Processing 1/1: /home/sohan/.retriever/raw_data/conus/CONUS_Backcasting_y1958.tif
NOTICE:  table "conus_backcasting_y1958" does not exist, skipping
Downloading CONUS_Backcasting_y1984.tif: 13.5kB [15:17, 15.1B/s]                                                                                                         
Processing 1/1: /home/sohan/.retriever/raw_data/conus/CONUS_Backcasting_y1984.tif
NOTICE:  table "conus_backcasting_y1984" does not exist, skipping
```
Similarly, It is downloading all the TIF file.

**Comment by henrykironde** [comment]
That `Notice` is fine. Check the data, It should be there regardless of the `Notice`

**Comment by Sohan022** [comment]
All the data(image file) downloaded inside the directory `/home/sohan/.retriever/raw_data/conus/`

**Comment by henrykironde** [comment]
And what about the Postgres screenshot?

**Comment by Sohan022** [comment]
```
sohan@ubuntu-user:~$ psql -d postgres -U postgres -d testdb_retriever
psql (13.2 (Ubuntu 13.2-1.pgdg18.04+1))
Type "help" for help.

testdb_retriever=# \dt
               List of relations
  Schema  |      Name       | Type  |  Owner   
----------+-----------------+-------+----------
 public   | spatial_ref_sys | table | postgres
 topology | layer           | table | postgres
 topology | topology        | table | postgres
(3 rows)

testdb_retriever=# 
```
In testdb_retriever, It is only showing three schemas. It is not showing iris and conus dataset. why?

**Comment by Aakash3101** [comment]
```
(gsoc-dev) aakash01@aakash01-G3-3579:~$ psql -U postgres
psql (13.2 (Ubuntu 13.2-1.pgdg20.04+1))
Type "help" for help.

postgres=# SELECT *
FROM pg_catalog.pg_tables
WHERE schemaname != 'pg_catalog' AND  schemaname != 'information_schema';
```
Try this, this command will print the tables present in the database. Maybe the data is in postgres database.

**Comment by Sohan022** [comment]
> And what about the Postgres screenshot?

Screenshot from 2021-03-24 19-47-59

**Comment by Sohan022** [comment]
```
postgres=# SELECT table_schema,table_name
FROM information_schema.tables
WHERE table_schema = 'conus';
 table_schema |       table_name        
--------------+-------------------------
 conus        | conus_backcasting_y1981
 conus        | conus_backcasting_y1958
 conus        | conus_backcasting_y1953
 conus        | conus_backcasting_y1991
 conus        | conus_backcasting_y1989
 conus        | conus_backcasting_y1944
 conus        | conus_backcasting_y1945
 conus        | conus_backcasting_y1960
 conus        | conus_backcasting_y1984
 conus        | conus_backcasting_y1975
 conus        | conus_backcasting_y1990
 conus        | conus_backcasting_y1946
 conus        | conus_backcasting_y1959
 conus        | conus_backcasting_y1970
 conus        | conus_backcasting_y1967
 conus        | conus_backcasting_y1982
 conus        | conus_backcasting_y1942
 conus        | conus_backcasting_y1974
 conus        | conus_backcasting_y1947
 conus        | conus_backcasting_y1965
 conus        | conus_backcasting_y1964
 conus        | conus_backcasting_y1940
 conus        | conus_backcasting_y1955
 conus        | conus_backcasting_y1972
 conus        | conus_backcasting_y1977
 conus        | conus_backcasting_y1980
 conus        | conus_backcasting_y1938
 conus        | conus_backcasting_y1985
 conus        | conus_backcasting_y1943
 conus        | conus_backcasting_y1941
 conus        | conus_backcasting_y1968
 conus        | conus_backcasting_y1987
 conus        | conus_backcasting_y1978
 conus        | conus_backcasting_y1962
```
Similarly, all the row are showing

**Comment by Sohan022** [comment]
Thanks @henrykironde @Aakash3101 

I think, The testing part is complete now.

**Comment by Aakash3101** [comment]
This is probably because of the [```postgres.py```](https://github.com/weecology/retriever/blob/main/retriever/engines/postgres.py) in ```retriever/engines```. 
In the ```Engine``` class, the default name for the database is postgres, and in our ```.pgpass``` file we don't supply the name of the database
```
required_opts = [
        ("user", "Enter your PostgreSQL username", "postgres"),
        ("password", "Enter your password", ""),
        ("host", "Enter your PostgreSQL host", "localhost"),
        ("port", "Enter your PostgreSQL port", 5432),
        ("database", "Enter your PostgreSQL database name", "postgres"),
        ("database_name", "Format of schema name", "{db}"),
        ("table_name", "Format of table name", "{db}.{table}"),
    ]
```

**Comment by henrykironde** [comment]
I recommend you use Pgadmin to visualize the tables. With such visualization you would have noticed that the datasets end up in Postgres the default database. The database `testdb_retriever` is used for testing by `pytest`

**Comment by henrykironde** [comment]
@Sohan022 good job on this.

I Managed to get the data installed and viewed used QGIS
Screen Shot 2021-04-05 at 9 11 57 PM

A few things we need to change. The name should be `'sohl-land-use-cover'` and file name `sohl_land_use_cover.json`.
In a few hours I will put in a PR to `retriever` and I think It will help to reduce the size of the file used in QGIS. You could test that after and let me know.

The installation time is normal.(About 1 and 1/2 hours for 55 files on a fully overloaded computer with many apps open).

**Comment by henrykironde** [comment]
The homepage link should be https://www.sciencebase.gov/catalog/item/59d3c73de4b05fe04cc3d1d1

**Pull request closed without merging**
