### PR TITLE
Fixed kaggle scripts from #65-68 and #60

### PR DESCRIPTION
**Pull request by Kadam-Tushar**
Modified scripts from #65 #66 #67 #68 #60 
- Fixed typos like adding "kaggle" and "data_source" field in every kaggle scripts
- Fixed urls of some datasets to  "Author/dataset_name"  (kaggle api format)

### CODE REVIEW

**Comment by henrykironde** [comment]
Thanks @Kadam-Tushar, we shall need to update the PR commits to include the original authors. I will review the PR in about 7-10 hours from now

**Comment by henrykironde** [comment]
Great, I will test this PR after the suggested edits. Since we have authors who started this work. I recommend the you commit each group of work in a single commit and add the respective author, i.e  `git commit --author="John Doe <john@doe.org>"`

For keywords: Include the keyword `kaggle dataset` for scripts that fall under datasource of `dataset`. Like wise add `kaggle competition` for the scripts with datasource as `competition`

**Comment by Kadam-Tushar** [comment]
@henrykironde  Let me confirm if I understand correctly :
I need to make 2 separate **new** commits for each author right? (As there only 2 authors) 
or 
As I have already committed then I will have to use something like `git commit  --amend --author="John Doe <john@doe.org>"` this right? But then how can I add another author for this single commit?

**Comment by ethanwhite** [comment]
@Kadam-Tushar You can find out more about how to add multiple authors to a commit here:
https://docs.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors

Normally we do this from the command line using the "Co-authored-by" addition to the commit message.

If you already have all of the commits it is possible to change the commit messages, though it's a bit more advanced git work. You start by doing an interactive rebase using

`git rebase -i HEAD~5`

where the 5 indicates how many commits back from the current commit to include.  This will open an editor with those commits listed. For the commits where you want to change the commit messages change the work `pick` to `reword`. Then save and exit and you'll have an editor open with the first commit, edit the commit message, save and exit, the next message to be edited will open.

**Comment by henrykironde** [comment]
Thanks @ethanwhite. Just a note, we are closing this PR we decided to create two new PR for these changes.

**Comment by Kadam-Tushar** [comment]
@ethanwhite  Thanks I will definitely try this out on my test repositories as it will help me learn more about git. But as @henrykironde  advised me, it will be easy for me to make 2 new separate PRs. :smile:

**Comment by ethanwhite** [comment]
Sounds like a good plan.

**Comment by Kadam-Tushar** [comment]
Closing this because there are some errors in scripts which are corrected in #89

**Pull request closed without merging**
