### PR TITLE
Updated mammal-community-db encoding

### PR DESCRIPTION
**Pull request by DumbMachine**
Added encoding for the dataset in script. "encoding": "latin-1". Attempts to close[[#1431](https://github.com/weecology/retriever/issues/1431).

### CODE REVIEW

**Comment by henrykironde** [comment]
I think we have the same in retriever-recipes.
Also you should update the version.txt
using` Python version.py`

**Comment by DumbMachine** [comment]
> I think we have the same in retriever-recipes.

This is the `retriever-recipes` version. I think you are talking about [the one in retriever/scripts](https://github.com/weecology/retriever/blob/master/scripts/mammal_community_db.json).

>Also you should update the version.txt
using Python version.py

Nothing seemed to change after executing `python version.py`.

**Comment by henrykironde** [comment]
First bump the version number to "version": "1.2.2"

**Comment by henrykironde** [comment]
This needs to be updated

**Comment by henrykironde** [comment]
Could we also update the retriever/script file in the same way

**Pull request merged**
