### PR TITLE
Update scripts with the latest changes

### PR DESCRIPTION
**Pull request by harshitbansal05**

### CODE REVIEW

**Comment by henrykironde** [comment]
This does not seem as a complete list of changes from master.
Looks like these changes may be missing 
```j
	scripts/biotimesql.py
	scripts/catalogos_dados_brasil.json
	scripts/predicts.py
	scripts/transparencia_dados_abertos_brasil.json
```
Checkout retriever, master branch and  retriever-recipes update-scripts branch. 
Copy the scripts from retriever/scripts to  retriever-recipes/scripts.
You will be able to use git status and git diff to confirm the required changes

**Comment by henrykironde** [comment]
Could we break down the test modified to have something like `test_on_[Engine]`, ie `test_on_sqlite()`

**Comment by henrykironde** [comment]
> the datasets take a large amount of time to install. Thus, the travis fails due to timeout.

That is true @harshitbansal05. We should change test modified to have smaller tests like I said. 
We should then comment it out for these two PRs.

A better way is to have test modified to skip on travis and on appveyor, but to run locally.
We have done something like that in the rdataretriever and also you could set up a new environmental variable that would be check like this env https://github.com/weecology/retriever/blob/master/docker-compose.yml#L35

**Comment by harshitbansal05** [comment]
@henrykironde sorry, but then what would be the whole point of having travis?

**Comment by harshitbansal05** [comment]
@henrykironde ^.

**Comment by zhangcandrew** [comment]
Hey Harshit, Travis is mainly used for continuous integration. It's ok to have smaller tests and it might be better to have a batch of smaller tests that can run to completion so travis doesn't time out instead of one big one that takes too long to run. This way instead of seeing the test just succeed or fail, we can see which exact engines it is failing on (xml, csv, json, postgres) etc.

**Comment by harshitbansal05** [comment]
@zhangcandrew @henrykironde done with the splitting part.

**Comment by henrykironde** [comment]
This passes for me locally, let's go on and skip tests on sqlite for now. We could do something like `pytest -v -k" not sqlite".`

**Pull request closed without merging**
