### PR TITLE
Add scripts and script editing functionalities

### PR DESCRIPTION
**Pull request by harshitbansal05**

### CODE REVIEW

**Comment by zhangcandrew** [comment]
Hey Harshit, thanks for this PR!

Do you think it'd be possible to split this up into 3 or 4 smaller PR's? It'd help me look through them. I think the commits are fine, but squashing some into one might help too ( like the inital retriever scripts commit, update scripts commit, and moving five legacy scripts commit) :)

**Comment by harshitbansal05** [comment]
@zhangcandrew I squashed the commits related to adding the scripts. Hope this helps.

**Comment by henrykironde** [comment]
@harshitbansal05, like Andrew said, I too think it would be better if you separate the this PR into smaller PRs.

**Comment by henrykironde** [comment]
@harshitbansal05, can we have a PR that only has scripts(make sure they are up to date). This will ease things up. The rest should be smaller PR's related.

**Comment by harshitbansal05** [comment]
@henrykironde the [pr](https://github.com/weecology/retriever-recipes/pull/4) that got merged contained only the scripts and the version.txt. Is that not fine?

**Comment by henrykironde** [comment]
Ah, thanks for making that clear. We can now clean up this PR. 👍

**Pull request closed without merging**
