### PR TITLE
Add WorldClim variables at 30 seconds, 5, 10, 2.5 minutes

### PR DESCRIPTION
**Pull request by henrykironde**
minimum temperature (°C),
maximum temperature (°C),
precipitation (mm),
solar radiation (kJ m-2 day-1),
wind speed (m s-1),
water vapor pressure (kPa),
Bioclimatic variables"

### CODE REVIEW

**Comment by ethanwhite** [comment]
LGTM. Is this ready for merge?

**Comment by henrykironde** [comment]
Nope let me make some more last meet tests and go through the json file. I will put a ready flag. Thank you.

**Comment by henrykironde** [comment]
Sample output from installed data
image

**Comment by henrykironde** [comment]
@ethanwhite

**Comment by henrykironde** [comment]
We wait for the changes from worldclim

Screen Shot 2020-03-09 at 9 23 53 PM

**Comment by ethanwhite** [comment]
:rofl:

**Pull request merged**
